max_age: "1h"
loglevel: error

email:
  enabled: true
  host: smtp.mailserver.com
  port: 587
  username: user
  password: pass
  from: from@localhost
  to: to@localhost

console:
  enabled: true

influxdb:
  addr: http://localhost:8086
  database: ruuvitag
  measurement: ruuvitag
  username: user
  password: pass
