max_age: 600
email_sent_file: influxdb-alerter.email.sent
influxdb:
  host: localhost
  port: 8086
  database: ruuvitag
  measurement: ruuvitag_sensor
  username: user
  password: pass
smtp:
  host: smtp.purelymail.com
  port: 587
  username: user
  password: pass
